print("Welcome to the food oredering Chatbot")
name = input("What is your name? ")
age = input("Hello " + name + " , how old are you? ")
print(" How may I assist you ")
print("1. Schedule")
print("2. Available products")
print("3. Exit")
option = input("")
if option == "3":
   print("Goodbye, have a nice day")
